version: '3.8'
networks:
  dev:
services:
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    networks:
      - dev
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: "postgresql+asyncpg://user:mysecretpassword@db:5432/dbname"
    ports:
      - "8000:8000"
    networks:
      - dev
    depends_on:
      - db

volumes:
  postgres_data:
