[project]
name = "full-app-pavel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.5",
    "python-multipart>=0.0.19",
    "uvicorn[standard]>=0.32.1",
]
